export const ADMIN_PERMISSION_BIT = 5;

export const MILISECONDS_PER_SECOND = 1000;
export const SECONDS_PER_MINUTE = 60;
const MINUTES_PER_HOUR = 60;
export const SECONDS_PER_HOUR = SECONDS_PER_MINUTE * MINUTES_PER_HOUR;
const HOURS_PER_DAY = 24;
export const SECONDS_PER_DAY = SECONDS_PER_HOUR * HOURS_PER_DAY;
